name: SharpEnchantments
version: '${version}'
main: com.nextdevv.sharpenchantments.SharpEnchantments
load: STARTUP
commands:
  enchantsharp:
    usage: /<command>
  enchgui:
    usage: /<command>
  getEnchant:
    usage: /<command>